from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Optional

from .lisp_eval import ListExpr, LispEvaluator, Symbol, parse_program, render_value


@dataclass(frozen=True)
class DifficultyConfig:
    stage: int
    depth: int = 1
    operator_set: tuple[str, ...] = ("+", "-", "*", "/")
    value_range: tuple[int, int] = (0, 9)
    collection_size: int = 3
    nesting_level: int = 1
    available_forms: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not 1 <= self.stage <= 7:
            raise ValueError("stage must be in the range [1, 7].")
        if self.depth <= 0:
            raise ValueError("depth must be positive.")
        if self.value_range[0] > self.value_range[1]:
            raise ValueError("value_range must be ordered as (min, max).")
        if self.collection_size <= 0:
            raise ValueError("collection_size must be positive.")
        if self.nesting_level <= 0:
            raise ValueError("nesting_level must be positive.")


@dataclass(frozen=True)
class ProblemExample:
    prompt_expression: str
    expected_result: object
    difficulty: DifficultyConfig
    metadata: dict[str, object] = field(default_factory=dict)

    @property
    def expected_result_text(self) -> str:
        return render_value(self.expected_result)


def default_difficulty_for_stage(stage: int) -> DifficultyConfig:
    return {
        1: DifficultyConfig(stage=1, depth=2, operator_set=("+", "-", "*", "/", "mod", "expt"), value_range=(0, 4)),
        2: DifficultyConfig(stage=2, depth=2, operator_set=("+", "-", "*", "/", "mod", "expt"), value_range=(0, 5)),
        3: DifficultyConfig(stage=3, depth=2, operator_set=("+", "-", "*"), value_range=(0, 5)),
        4: DifficultyConfig(stage=4, depth=2, operator_set=("+", "-", "*"), value_range=(0, 5)),
        5: DifficultyConfig(stage=5, depth=2, operator_set=("+", "-", "*", "expt"), value_range=(0, 5)),
        6: DifficultyConfig(stage=6, depth=2, operator_set=("+", "-", "*"), value_range=(0, 5)),
        7: DifficultyConfig(stage=7, depth=2, operator_set=("+", "-", "*"), value_range=(0, 5), collection_size=3),
    }[stage]


class ProblemGenerator:
    def __init__(self, rng: Optional[random.Random] = None) -> None:
        self.rng = rng or random.Random()

    def generate_problem(self, difficulty: DifficultyConfig) -> ProblemExample:
        if difficulty.stage == 6:
            return self._stage_six_problem(difficulty)
        prompt = self._prompt_for_stage(difficulty)
        expected = LispEvaluator(stage=difficulty.stage).evaluate_program(prompt)
        return ProblemExample(prompt_expression=prompt, expected_result=expected, difficulty=difficulty)

    def generate_batch(self, difficulties: list[DifficultyConfig]) -> list[ProblemExample]:
        return [self.generate_problem(difficulty) for difficulty in difficulties]

    def _prompt_for_stage(self, difficulty: DifficultyConfig) -> str:
        stage = difficulty.stage
        if stage == 1:
            return self._arithmetic(difficulty, difficulty.depth)
        if stage == 2:
            return self._stage_two(difficulty)
        if stage == 3:
            return self._stage_three(difficulty)
        if stage == 4:
            return self._stage_four(difficulty)
        if stage == 5:
            return self._stage_five(difficulty)
        if stage == 6:
            raise AssertionError("Stage 6 proof problems are generated by _stage_six_problem.")
        return self._stage_seven(difficulty)

    def _literal(self, difficulty: DifficultyConfig, *, non_zero: bool = False) -> int:
        low, high = difficulty.value_range
        value = self.rng.randint(low, high)
        if non_zero and value == 0:
            candidates = [candidate for candidate in range(low, high + 1) if candidate != 0]
            value = self.rng.choice(candidates) if candidates else 1
        return value

    def _arithmetic(self, difficulty: DifficultyConfig, depth: int) -> str:
        if depth <= 1:
            return str(self._literal(difficulty))
        operator = self.rng.choice(difficulty.operator_set)
        if operator == "/":
            divisor = self._literal(difficulty, non_zero=True)
            quotient = self._literal(difficulty)
            return f"(/ {quotient * divisor} {divisor})"
        if operator == "mod":
            divisor = self._literal(difficulty, non_zero=True)
            dividend = self._literal(difficulty) + divisor
            return f"(mod {dividend} {divisor})"
        if operator == "expt":
            base = self._literal(difficulty)
            power = self.rng.randint(0, 3)
            return f"(expt {base} {power})"
        left = self._arithmetic(difficulty, depth - 1)
        right = self._arithmetic(difficulty, depth - 1)
        return f"({operator} {left} {right})"

    def _stage_two(self, difficulty: DifficultyConfig) -> str:
        if self.rng.random() < 0.5:
            x_expr = self._arithmetic(difficulty, max(1, difficulty.depth - 1))
            return f"(let [x {x_expr}] (* x 2))"
        if self.rng.random() < 0.7:
            left = self._arithmetic(difficulty, max(1, difficulty.depth - 1))
            right = self._arithmetic(difficulty, max(1, difficulty.depth - 1))
            comparator = self.rng.choice(("=", "<", ">", "<=", ">="))
            return f"({comparator} {left} {right})"
        return f"(and (> {self._literal(difficulty)} 0) (not (= {self._literal(difficulty)} 99)))"

    def _stage_three(self, difficulty: DifficultyConfig) -> str:
        if self.rng.random() < 0.5:
            return f"(quote (+ {self._literal(difficulty)} {self._literal(difficulty)}))"
        if self.rng.random() < 0.5:
            return f"(list {self._literal(difficulty)} (+ 1 2) :foo)"
        return f"(list :eval (eval (quote (+ {self._literal(difficulty)} {self._literal(difficulty)}))))"

    def _stage_four(self, difficulty: DifficultyConfig) -> str:
        value = self._literal(difficulty)
        choice = self.rng.choice(("if", "cond", "lambda", "define"))
        if choice == "if":
            return f"(if (> {value} 0) (+ {value} 1) 0)"
        if choice == "cond":
            return f"(cond (= {value} 0) 0 :else (* {value} 2))"
        if choice == "lambda":
            return f"((lambda [x] (+ x 2)) {value})"
        return f"(define double (lambda [x] (* x 2))) (double {value})"

    def _vector_literal(self, difficulty: DifficultyConfig) -> str:
        values = [str(self._literal(difficulty)) for _ in range(difficulty.collection_size)]
        return "[" + " ".join(values) + "]"

    def _stage_five(self, difficulty: DifficultyConfig) -> str:
        choice = self.rng.choice(("simplify", "expand", "substitute", "differentiate"))
        if choice == "simplify":
            return "(simplify (quote (+ x 0)))"
        if choice == "expand":
            return "(expand (quote (* x (+ x 1))))"
        if choice == "substitute":
            return f"(substitute (quote (+ x 1)) (quote x) {self._literal(difficulty)})"
        return "(differentiate (quote (* x x)) (quote x))"

    def _stage_six_problem(self, difficulty: DifficultyConfig) -> ProblemExample:
        premise = parse_program("(+ x 0)")[0]
        target = parse_program("x")[0]
        prompt = "(prove x from (+ x 0))"
        proof = "(step simplify-add-zero (+ x 0) x)"
        return ProblemExample(
            prompt_expression=prompt,
            expected_result=target,
            difficulty=difficulty,
            metadata={
                "premises": (premise,),
                "target": target,
                "example_solution": proof,
            },
        )

    def _stage_seven(self, difficulty: DifficultyConfig) -> str:
        vector = self._vector_literal(difficulty)
        choice = self.rng.choice(("get", "count", "assoc", "mapv", "filterv", "reduce", "thread-first", "thread-last", "comp"))
        if choice == "get":
            index = self.rng.randrange(difficulty.collection_size)
            return f"(get {vector} {index})"
        if choice == "count":
            return f"(count {vector})"
        if choice == "assoc":
            return f"(assoc {{:a 1 :b 2}} :c 3)"
        if choice == "mapv":
            return f"(mapv (lambda [x] (* x 2)) {vector})"
        if choice == "filterv":
            return f"(filterv (lambda [x] (> x 1)) {vector})"
        if choice == "reduce":
            return f"(reduce + 0 {vector})"
        if choice == "thread-first":
            return "(-> 3 (+ 4) (* 2))"
        if choice == "thread-last":
            return f"(->> {vector} (mapv (partial + 1)) (reduce + 0))"
        return "((comp (partial * 2) (partial + 3)) 4)"


__all__ = [
    "DifficultyConfig",
    "ProblemExample",
    "ProblemGenerator",
    "default_difficulty_for_stage",
]
